title: Scratch video intro test
hero_image: images/banner.png
description: Testing how the video intro looks
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
